import type { Metadata } from "next";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { StaffProvider } from "./contexts/StaffContext";
import Alert from "@/components/Alert";
import { AlertProvider } from "./contexts/AlertContext";
import AlertPrompt from "@/components/AlertPrompt";

config.autoAddCss = false;


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <StaffProvider>
          <AlertProvider>
            <AlertPrompt />
            {children}
          </AlertProvider>
        </StaffProvider>
      </body>
    </html>
  );
}
