import type { Metadata } from "next";
import "./globals.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { StaffProvider } from "./contexts/StaffContext";
import { AlertProvider } from "./contexts/AlertContext";
import AlertPrompt from "@/components/AlertPrompt";
import { ConfirmPromptProvider } from "./contexts/ConfirmContext";
import ConfirmPrompt from "@/components/ConfirmPrompt";
import { LoadingProvider } from "./contexts/LoadingContext";
import NavigationEvents from "@/components/NavigationEvents";
import { SidebarProvider } from "./contexts/SidebarContext";

config.autoAddCss = false;


export const metadata: Metadata = {
  title: "Student Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <LoadingProvider>
          <ConfirmPromptProvider>
            <StaffProvider>
              <AlertProvider>
                <SidebarProvider>
                  <ConfirmPrompt />
                  <AlertPrompt />
                  <NavigationEvents />
                  {children}
                </SidebarProvider>
              </AlertProvider>
            </StaffProvider>
          </ConfirmPromptProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
